spring:
  application:
    name: Apigateway
  config:
    import: optional:configserver:http://sparta24:sparta24@localhost:9000
  spring:
    security:
      csrf:
        enabled: false  # CSRF 보호 비활성화