version: '3.8'

services:
  postgresql_order:
    image: 'bitnami/postgresql:latest'
    networks:
      - postgres_network
    environment:
      - POSTGRESQL_USERNAME=order
      - POSTGRESQL_PASSWORD=order
      - POSTGRESQL_DATABASE=order
      - POSTGRESQL_ROOT_PASSWORD=rootpassword
    ports:
      - "25434:5432"
  postgresql_auth:
    image: 'bitnami/postgresql:latest'
    networks:
      - postgres_network
    environment:
      - POSTGRESQL_USERNAME=auth
      - POSTGRESQL_PASSWORD=auth
      - POSTGRESQL_DATABASE=auth
      - POSTGRESQL_ROOT_PASSWORD=rootpassword
    ports:
      - "25435:5432"
  postgresql_company:
    image: 'bitnami/postgresql:latest'
    networks:
      - postgres_network
    environment:
      - POSTGRESQL_USERNAME=company
      - POSTGRESQL_PASSWORD=company
      - POSTGRESQL_DATABASE=company
      - POSTGRESQL_ROOT_PASSWORD=rootpassword
    ports:
      - "25436:5432"
  postgresql_hub:
    image: 'bitnami/postgresql:latest'
    networks:
      - postgres_network
    environment:
      - POSTGRESQL_USERNAME=hub
      - POSTGRESQL_PASSWORD=hub
      - POSTGRESQL_DATABASE=hub
      - POSTGRESQL_ROOT_PASSWORD=rootpassword
    ports:
      - "25437:5432"
  postgresql_message:
    image: 'bitnami/postgresql:latest'
    networks:
      - postgres_network
    environment:
      - POSTGRESQL_USERNAME=message
      - POSTGRESQL_PASSWORD=message
      - POSTGRESQL_DATABASE=message
      - POSTGRESQL_ROOT_PASSWORD=rootpassword
    ports:
      - "25438:5432"

  redis:
    image: 'redis:latest'  # Redis 이미지 사용
    hostname: redis
    command: redis-server --requirepass systempass --port 6379
    networks:
      - postgres_network  # 동일 네트워크 사용
    ports:
      - "25439:6379"  # 바인딩할 포트:내부 포트

networks:
  postgres_network:
    driver: bridge