spring:
  application:
    name: MessageService
  config:
    import: optional:configserver:http://sparta24:sparta24@localhost:9000
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:25438/message
    username: message
    password: message

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 1000