spring:
  application:
    name: AuthService
  config:
    import: optional:configserver:http://sparta24:sparta24@localhost:9000
  datasource:
    url: jdbc:postgresql://localhost:25435/auth
    username: auth
    password: auth
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"